### ISSUE TITLE
Only custom type "tel" can have a predefiend value

### ISSUE THREAD

**Issue by NordicAngel** [wiseaidev/input-yew#8]
As far as I can read from the code and some limited testing the only type that can be assigned a starting value is the "tel" type as that is the only input_tag in the match statement that has the line:
```
<input
    ...
    value={(*props.input_handle).clone()}
    ...
</input>
```

**Comment by wiseaidev** [comment]
There is no need to expose the `value` attribute for the user since it is already handled by [`use_node_ref`](https://api.yew.rs/next/yew/functional/fn.use_node_ref.html) and [`use_state`](https://api.yew.rs/next/yew/functional/fn.use_state.html). If you want to set a default value, you can do so using `use_state` with an initial value. For more info, have a look [at this example](https://github.com/wiseaidev/yew-components-tailwind/blob/main/src/components/multi_step_form_one.rs):

```rust
    let input_full_name_ref = use_node_ref();
    let input_full_name_handle = use_state(String::default); // <--- set your initial value here

                   <CustomInput
                      input_handle={input_full_name_handle}
                      input_ref={input_full_name_ref}
                    />
```

**Comment by NordicAngel** [comment]
This is what I meant didn't work if I use 
´´´
    let isbn_handle = use_state(|| "hello".to_string());
´´´
my input field only show "hello" if it is of type "tel" and not if it is of type "text".

**Comment by wiseaidev** [comment]
Thanks for the follow-up. I can reproduce the issue now. But as far as I can remember, it was working as expected. That's weird! Probably yew 0.21 introduced some changes to these hooks. Lemme see what's wrong!
